name: Tägliche WhatsApp-Nachrichten

on:
  schedule:
    # Jeden Tag um 7:00 Uhr (UTC+2 -> 5:00 UTC)
    - cron: '0 5 * * *'
    # Jeden Tag um 15:00 Uhr nach der Schule (UTC+2 -> 13:00 UTC)
    - cron: '0 13 * * *'
  workflow_dispatch:  # Ermöglicht manuelle Auslösung im GitHub-Interface

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Installiere Abhängigkeiten
        run: npm ci

      - name: Stelle sicher, dass Chromium installiert ist
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      
      - name: Lade WhatsApp-Session
        uses: actions/cache@v3
        with:
          path: .wwebjs_auth
          key: ${{ runner.os }}-wwebjs-auth

      - name: Sende Nachricht
        env:
          SEND_MESSAGE: 'true'
          WHATSAPP_GROUP_ID: ${{ secrets.WHATSAPP_GROUP_ID }}
          # TIME_OF_DAY zeigt an, ob es morgens oder nachmittags ist
          TIME_OF_DAY: ${{ github.event.schedule == '0 5 * * *' && 'morning' || 'afternoon' }}
        run: node index.js 