name: Schulkalender Aktualisierung

on:
  schedule:
    # Jeden Tag um 2:00 Uhr nachts (UTC), vor den Benachrichtigungen
    - cron: '0 2 * * *'
  workflow_dispatch:  # Ermöglicht manuelle Auslösung

# Explizite Schreibberechtigung für das Repository hinzufügen
permissions:
  contents: write

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Installiere Abhängigkeiten
        run: npm ci

      - name: Stelle sicher, dass csv-parser installiert ist
        run: npm install csv-parser

      - name: Stelle sicher, dass Chromium installiert ist
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Erstelle Downloads-Verzeichnis
        run: mkdir -p downloads
      
      - name: Aktualisiere Kalender mit automatischer Schulportal-Verbindung
        env:
          SCHULPORTAL_USERNAME: ${{ secrets.SCHULPORTAL_USERNAME }}
          SCHULPORTAL_PASSWORD: ${{ secrets.SCHULPORTAL_PASSWORD }}
          CSV_FILE: ${{ github.workspace }}/SPH-Schulkalender-Khalaf.csv
        run: node update-schedule.js
      
      - name: Commite geänderte schedule.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Prüfen ob Änderungen in schedule.json vorhanden sind
          git add schedule.json
          if git diff --staged --quiet; then
            echo "Keine Änderungen in schedule.json gefunden."
          else
            git commit -m "Automatische Aktualisierung des Schulkalenders"
            git push
          fi
          
      # Optional: Wenn neue CSV-Dateien heruntergeladen wurden, füge sie auch zum Repository hinzu
      - name: Prüfe und commite neue CSV-Dateien
        run: |
          if [ -d "downloads" ] && [ "$(ls -A downloads/)" ]; then
            cp downloads/*.csv . 2>/dev/null || true
            git add *.csv
            if git diff --staged --quiet; then
              echo "Keine neuen CSV-Dateien gefunden."
            else
              git commit -m "Neue CSV-Dateien vom Schulportal hinzugefügt"
              git push
            fi
          fi 