name: Schulkalender Aktualisierung

on:
  schedule:
    # Jeden Tag um 2:00 Uhr nachts (UTC), vor den Benachrichtigungen
    - cron: '0 2 * * *'
  workflow_dispatch:  # Ermöglicht manuelle Auslösung

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Installiere Abhängigkeiten
        run: npm ci

      - name: Stelle sicher, dass Chromium installiert ist
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Aktualisiere Kalender
        env:
          SCHULPORTAL_USERNAME: ${{ secrets.SCHULPORTAL_USERNAME }}
          SCHULPORTAL_PASSWORD: ${{ secrets.SCHULPORTAL_PASSWORD }}
        run: node update-schedule.js

      - name: Commite geänderte schedule.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add schedule.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatische Aktualisierung des Schulkalenders"
          git push 